# Generated by Django 4.1.5 on 2023-02-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perro',
            old_name='salud',
            new_name='datos',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='tamaño',
        ),
    ]
