# Generated by Django 4.1.5 on 2023-02-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerros', '0002_rename_salud_perro_datos_remove_perro_tamaño'),
    ]

    operations = [
        migrations.CreateModel(
            name='HogarTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=40)),
                ('datoshogar', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Hogar_Temporal',
        ),
    ]
